#!/bin/bash

CSV=csv_files

python3 doorstop_yml_formatter.py
if [ $? -ne 0 ]; then
    echo "FAILURE, exiting build."
    exit 1
fi

python3 doorstop_hooks.py
if [ $? -eq 0 ]; then
    doorstop publish all public/ # This may not scale
    rm -rf ./$CSV
    doorstop export all ./$CSV # This may not scale
else
    echo "FAILURE, exiting build."
    exit 1
fi

exit 0