attributes:
  defaults:
    rationale: null
    type: Requirement
    verified-by: unverified
  publish:
  - verified-by
  - type
  - rationale
settings:
  digits: 4
  parent: REQ
  prefix: FLIGHT
  sep: '-'
